### ISSUE TITLE
pyramid_sparse.py error

### ISSUE THREAD

**Issue by cooketho** [koszullab/GRAAL#10]
I used HiC-Box to pre-process my data, and loaded it into GRAAL. I clicked 'build pyramid' and it reported that the pyramid was built. I then started GRAAL, and after a few minutes, it gave the error below. I'm not sure if this worked correctly--I will send you a link to my data if you care to try and reproduce the error. I got GRAAL to work fine on the test data set, so I wonder if it is some problem with how I processed my data. Please let me know if you can help. Thanks!

25204
25205
25206
25207
25208
25209
25210
25211
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in **bootstrap_inner
    self.run()
  File "main_window.py", line 425, in run
    self)
  File "/home/tom/Desktop/test/GRAAL-master/main_gl.py", line 81, in __init**
    self.fasta_file, candidates_blacklist, self.allow_repeats)
  File "/home/tom/Desktop/test/GRAAL-master/simulation_loader.py",
line 66, in **init**
    self.level.build_seq_per_bin(genome_fasta=fasta_file) #
  File "/home/tom/Desktop/test/GRAAL-master/pyramid_sparse.py", line
1419, in build_seq_per_bin
    start = frag.start_pos
AttributeError: 'str' object has no attribute 'start_pos'

---
## PyCUDA ERROR: The context stack was not empty upon module cleanup.

A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
## Use Context.pop() to avoid this problem.

Aborted (core dumped)

**Comment by baudrly** [comment]
This should be fixed with my latest commit. Please delete the pyramid folder and try again, and if it fails again you can always link me to the data so I can look further into it.

**Comment by baudrly** [comment]
Closing this until this kind of issue pops up again.
