### ISSUE TITLE
make available the fasta.zip, S1.zip and tricho_qm6a

### ISSUE THREAD

**Issue by fransua** [koszullab/GRAAL#4]
Hi,
would it be possible for you to make these example file available in order to understand the input format.
thanks
thanks for the software.

**Comment by rkoszul** [comment]
Hi,

I updated the readme with links to the example datasets and genomes. I'm currently working on a detailed explanation on how to template your data if you want to do it manually.

**Comment by baudrly** [comment]
Closing this since links are up and the input format spec has been added to the readme.
