### ISSUE TITLE
How to download graal.zip?

### ISSUE THREAD

**Issue by lamz138138** [koszullab/GRAAL#6]
Hi!

I had read the paper of GRAAL. It was a grate work, and I want to try this software with my data. However, I couldn't find where to download graal.zip after go through the paper and here. I feel read me is to simple to use this tool. Besides, where are the pdf files that may be very useful?

Best wishes!

**Comment by rkoszul** [comment]
Hello, 

You can either clone the repository or get it [here](http://rsglab.weebly.com/uploads/3/0/5/7/30573875/graal.zip). Hope that helped!

**Comment by lamz138138** [comment]
Hi, thanks for your reply!

Is there any manual available? In my opinion, read me is not enough, there was pdf files stated in paper, can I get them?

Best wishes!

**Comment by rkoszul** [comment]
I've added a pdf that provides a more detailed explanation of the algorithm to the repo, is that what you wanted? If you run into any trouble trying to run the software, feel free to open an issue and we'll try to address it.

**Comment by lamz138138** [comment]
Hi, thanks very much!
